version: "3.8"
services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=123
    command:
      - mysql -uroot -p123
    image: task-manager-db
    ports:
      - '3005:3306'
    restart: always
  be:
    image: task-manager-be
    depends_on:
      - db
    ports: 
      - '3000:4000'
    links:
      - db:db