

CREATE TABLE USER_PRIVILEGES (
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    PRIVILEGE VARCHAR(25) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE TASK_VAL_PRIORITY (
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    PRIORITY VARCHAR(25) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE TASK_VAL_STATUS (
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    STATUS VARCHAR(25) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE USERS (
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    USERNAME VARCHAR(25) NOT NULL UNIQUE,
    PRIVILEGE_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PRIVILEGE_ID) REFERENCES USER_PRIVILEGES(ID)
);

CREATE TABLE TASKS (
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    DESCRIPTION TEXT,
    PRIORITY_ID INT NOT NULL,
    STATUS_ID INT NOT NULL,
    ACTIVITY_DATE DATE NOT NULL,
    CREATION_DATE DATE NOT NULL,
    UPDATED_BY VARCHAR(25) NOT NULL,
    CREATED_BY VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (PRIORITY_ID) REFERENCES TASK_VAL_PRIORITY(ID),
    FOREIGN KEY (STATUS_ID) REFERENCES TASK_VAL_STATUS(ID)
);

INSERT INTO TASK_VAL_PRIORITY (PRIORITY)
VALUES ('LOW'), ('MODERATE'), ('HIGH');

INSERT INTO TASK_VAL_STATUS (STATUS)
VALUES ('INCOMPLETE'), ('IN PROGRESS'), ('COMPLETE'), ('NONE');

INSERT INTO USER_PRIVILEGES (PRIVILEGE)
VALUES ('READ'), ('WRITE'), ('ADMIN');